spring:
  application:
    name: email-service

server:
  port: 8301
  
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-service:8302/eureka/


